#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 jvmName
  exit
 fi
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     versionMultiJvm.multiJVMStatique.DistributedCVM $1 config.xml

